### ISSUE TITLE
more accurate distance calculations by guessing positions of unpaired electrons?

### ISSUE THREAD

**Issue by katrinr** [MDAnalysis/RotamerConvolveMD#14]
An idea came to my mind just recently. In the experiments, they measure the distance between the unpaired electrons of the two labels. As the unpaired electron is "located" between N1 and O1, I would suggest to take also the distance between the two labels by using the mean of N1 (first label) to N1' (second label) and O1 (first label) to O1' (second label). Although this makes only a 1.3 A difference, it would make the output of the program more precise with just adding some lines of code.
Best wishes,
Katrin

**Comment by orbeckst** [comment]
I made the title more explicit and added the question label to show that right now it is a discussion. Once there is code/PR available we can remove the label.

The main question that I have is how are you going to validate the new approach over the old one, i.e., how will you know that you are improving?

**Comment by katrinr** [comment]
As written and shown in the literature, e.g. [Jeschke et al. 2013](http://www.sciencedirect.com/science/article/pii/S0079656513000393), the position of the free electron is between N1 and O1 (when using MTSL). Based on this information, the simulation with RotamerConvolveMD would be more precise by using the distances measured between N1 and O1. I think it is possible to show, that it slightly improves with the appropriate data. Unfortunately, I don't have published experimental DEER data now.

**Comment by orbeckst** [comment]
Didn't you implement guessing the electron position from N-O in 03f39fb9bf89f7867e50910441714d9b9272dece and later commits?

If so, we can close this issue.

**Comment by orbeckst** [comment]
ping @katrinr : is `convolve-mtss-rotamers_pre.py` the implementation?

Also, can you please check that the `--useNOelectron` flag is doing the right thing because using it seems to set `useNOelectron` to `True` which according to the docs _"True = N1 atoms used distance measurements,            False = geometic midpoints of N1 and O1 atoms used for distance calculation"_.

**Comment by orbeckst** [comment]
From @katrinr : 
> Thanks for pointing this out. It is correctly implemented and I double checked the code, but the documentation was wrong and I changed it.
