### ISSUE TITLE
MTSL label site 

### ISSUE THREAD

**Issue by MamtaMohan** [MDAnalysis/RotamerConvolveMD#17]
Hi,

I would like to know if via this software I can attach MTSL label to a site in protein replacing that residue as cysteine residues attached with label.

I am trying to simulate system in gromacs and I have never modified FF in gromacs.

Mamta

**Comment by lukas-stelzl** [comment]
Hi Matama,
with RotamerConvolve you cannot modify the FF in Gromacs. However, you can add the MTSL to a trajectory generated with Gromacs. 

Hope that helps a bit,
Lukas

**Comment by MamtaMohan** [comment]
Thank you for your response.

If I add label to the trajectory than what happens to the FF.

**Comment by lukas-stelzl** [comment]
The forcefield itself is not changed. RotamerConvolveMD allows you to explore the possible conformatiion of MTSL for each frame in your trajectory. The MTSL rotameres included in package come from Gunnar Jeschke's rotamer library for MTSL and in way a standin for adding MTSL to the force field. The nice thing about RotamerConvolveMD is that you don't need to modify the force field itselft to explore the effect of a MTSL spin label on your system.

**Comment by MamtaMohan** [comment]
I understand now.

Thank you.
