### ISSUE TITLE
include @katrinr as main author

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/RotamerConvolveMD#22]
@katrinr has been the main driving force behind recent updates and she should be one of the explicitly named authors in the output etc. — @philipwfowler are you happy with this?

@katrinr : have you got a paper where you used your additions (PRE, new rotamers)? If so we should add the paper and also ask people to cite it.

**Comment by katrinr** [comment]
@orbeckst, we hope to publish soon... :)

**Comment by philipwfowler** [comment]
Absolutely! Glad someone has been updating. Put me wherever is best for you in any list as well.

These are the papers I mainly wrote it for 
http://dx.doi.org/10.1016/j.str.2014.12.012
http://dx.doi.org/10.1016/j.jmb.2013.10.024

Am unlikely to be doing much DEER in the next few years...
