### ISSUE TITLE
Install recipe (for users with old NumPy versions)

### ISSUE THREAD

**Issue by lukas-stelzl** [MDAnalysis/RotamerConvolveMD#27]
A colleague, is struggling to install RotamerConvolveMD, the typical installation procedure via

pip install --user   RotamerConvolveMD

does not seem to work. I'll try to come up with an Anaconda based solution.

**Comment by orbeckst** [comment]
How does `pip` fail? 

A conda package would be nice.

There should also be a release 1.3.0, see #18...

**Comment by lukas-stelzl** [comment]
I'll ask whether I can share logs for the failed installation attempts.... I just got an email that it works now.. I`ll try to find out what made the difference and I will add to the documentation.

**Comment by orbeckst** [comment]
No more input – closing.
