### ISSUE TITLE
update author email address

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/RotamerConvolveMD#4]
@philipwfowler has a new email address, need to update docs and `setup.py`

**Comment by philipwfowler** [comment]
But my email address doesn't appear in either the docs or `setup.py` ??

**Comment by orbeckst** [comment]
in setup.py [L28](https://github.com/MDAnalysis/RotamerConvolveMD/blob/master/setup.py#L28)... you can just edit it through the GitHub web frontend. I just didn't know which email you'd like to put there.
