### ISSUE TITLE
release 1.2.0

### ISSUE THREAD

**Issue by orbeckst** [MDAnalysis/RotamerConvolveMD#7]
Being able to work with MDAnalysis >= 0.11 (#3) merits a release and we have also ascertained that there are no big bugs hiding under the bed (#6).

I'd also like to use [semantic versioning](http://semver.org) from now on so I suggest we release the current state as **1.2.0**.

I can also push a release to [PyPi RotamerConvolveMD](https://pypi.python.org/pypi/RotamerConvolveMD/1.0) if @philipwfowler adds me as a _Maintainer_.

Opinions, @MDAnalysis/rotamerconvolvemd and @kain88-de ?
- [x] release on GitHub (tag **[release-1.2.0](https://github.com/MDAnalysis/RotamerConvolveMD/releases/tag/release-1.2.0)**)
- [x] package on PyPi
- [ ] conda package

**Comment by kain88-de** [comment]
Should we release conda packages as well with the new release?

This is a pure python package so generating them is easy.

**Comment by orbeckst** [comment]
> On 21 May, 2016, at 02:05, kain88-de notifications@github.com wrote:
> 
> Should we release conda packages as well with the new release?
> 
> This is a pure python package so generating them is easy.

If you add the infrastructure then yes – might as well be consistent across everything under MDAnalysis.

**Comment by philipwfowler** [comment]
Oli = Maintainer on PyPi now. 

—Phil

**Comment by orbeckst** [comment]
@philipwfowler – I still cannot edit anything on PyPi. I am listed as a maintainer in the meta data but neither the web frontend nor `python setup.py upload` allows me to do anything. 

Did you go through the _Role_ link and added _Oliver.Beckstein_ as Maintainer?

**Comment by orbeckst** [comment]
I created the release https://github.com/MDAnalysis/RotamerConvolveMD/releases/tag/release-1.2.0 but could not upload the package to pypi (waiting on @philipwfowler).

@kain88-de can you do the conda (from the tag **release-1.2.0** because I will now bump the release numbers).

**Comment by philipwfowler** [comment]
Ok, try now. Added Oliver.Beckstein via Roles link as well as in the package. —Phil

**Comment by kain88-de** [comment]
@orbeckst I'll do the conda package tomorrow

**Comment by orbeckst** [comment]
Thanks @philipwfowler , packages for 1.2.0 are now on PyPi – as easy as 

```
git checkout release-1.2.0
python setup.py sdist bdist_egg bdist_wheel upload
```

Waiting for the conda package to close.

**Comment by kain88-de** [comment]
https://anaconda.org/MDAnalysis/rotcon

**Comment by orbeckst** [comment]
Thanks!

> On 26 May, 2016, at 14:53, kain88-de notifications@github.com wrote:
> 
> https://anaconda.org/MDAnalysis/rotcon
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub

## 

Oliver Beckstein \* orbeckst@gmx.net
skype: orbeckst  \* orbeckst@gmail.com
